package com.futou.cpcad.userCenter.db.dao;

import com.futou.cpcad.userCenter.db.domain.BillLog;
import com.futou.cpcad.userCenter.db.domain.BillLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    long countByExample(BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int deleteByExample(BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int insert(BillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int insertSelective(BillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BillLog selectOneByExample(BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BillLog selectOneByExampleSelective(@Param("example") BillLogExample example, @Param("selective") BillLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BillLog> selectByExampleSelective(@Param("example") BillLogExample example, @Param("selective") BillLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    List<BillLog> selectByExample(BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BillLog selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") BillLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    BillLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BillLog record, @Param("example") BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BillLog record, @Param("example") BillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BillLog record);
}