package com.futou.cpcad.userCenter.db.dao;

import com.futou.cpcad.userCenter.db.domain.UserCompany;
import com.futou.cpcad.userCenter.db.domain.UserCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    long countByExample(UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int deleteByExample(UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int insert(UserCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int insertSelective(UserCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserCompany selectOneByExample(UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserCompany selectOneByExampleSelective(@Param("example") UserCompanyExample example, @Param("selective") UserCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserCompany> selectByExampleSelective(@Param("example") UserCompanyExample example, @Param("selective") UserCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    List<UserCompany> selectByExample(UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserCompany selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") UserCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    UserCompany selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserCompany selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserCompany record, @Param("example") UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserCompany record, @Param("example") UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") UserCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(String id);
}