package com.futou.cpcad.userCenter.db.dao;

import com.futou.cpcad.userCenter.db.domain.UserWx;
import com.futou.cpcad.userCenter.db.domain.UserWxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    long countByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int deleteByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int insert(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int insertSelective(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserWx selectOneByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserWx selectOneByExampleSelective(@Param("example") UserWxExample example, @Param("selective") UserWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserWx> selectByExampleSelective(@Param("example") UserWxExample example, @Param("selective") UserWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    List<UserWx> selectByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserWx selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") UserWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    UserWx selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserWx record, @Param("example") UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserWx record, @Param("example") UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserWx record);
}