package com.futou.cpcad.userCenter.db.dao;

import com.futou.cpcad.userCenter.db.domain.UserMobile;
import com.futou.cpcad.userCenter.db.domain.UserMobileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    long countByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int deleteByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int insert(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int insertSelective(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserMobile selectOneByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserMobile selectOneByExampleSelective(@Param("example") UserMobileExample example, @Param("selective") UserMobile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserMobile> selectByExampleSelective(@Param("example") UserMobileExample example, @Param("selective") UserMobile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    List<UserMobile> selectByExample(UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserMobile selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") UserMobile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    UserMobile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMobile record, @Param("example") UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMobile record, @Param("example") UserMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mobile
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMobile record);
}